# Generated by Django 2.1.15 on 2020-06-14 04:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20200614_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rank_users',
            field=models.ManyToManyField(null=True, related_name='user_rank', through='movies.UserRank', to=settings.AUTH_USER_MODEL),
        ),
    ]
