# Generated by Django 2.1.15 on 2020-06-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20200614_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrank',
            name='rank',
            field=models.FloatField(default=0),
        ),
    ]
