# Generated by Django 2.1.15 on 2020-06-14 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20200614_1942'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rank',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.UserRank'),
        ),
    ]
