# Generated by Django 2.1.15 on 2020-06-16 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20200614_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rank',
        ),
    ]
