# Generated by Django 2.1.15 on 2020-06-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_remove_review_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rank',
            field=models.FloatField(default=0),
        ),
    ]
