# Generated by Django 2.1.15 on 2020-06-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favor_genres',
            field=models.TextField(blank=True),
        ),
    ]
