# Generated by Django 2.1.15 on 2020-06-15 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_favor_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favor_genres',
        ),
    ]
