# Generated by Django 2.1.15 on 2020-06-17 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_genrereview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genrereview',
            name='Genre',
        ),
        migrations.AddField(
            model_name='genrereview',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.Genre'),
        ),
    ]
