# Generated by Django 2.1.15 on 2020-06-17 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20200617_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genrereview',
            old_name='title',
            new_name='username',
        ),
    ]
